### ISSUE TITLE
Windows support on Travis CI

### ISSUE THREAD

**Issue by djhoese** [pyvista/gl-ci-helpers#2]
I'd like to try to get this working on Travis CI's Windows environments. I notice that the examples are specifically for Travis Linux. Has anyone tried OpenGL on Travis Windows?

Side note: I notice, at least on the machines I've tried on, that GitHub doesn't let you download a file as large as the VisPy `dll`s unless you add the `?raw=true` to the end of the URL.

CC @larsoner

**Comment by larsoner** [comment]
I've only ever used this on Azure and AppVeyor (successfully both places), I've never even worked with Travis's Windows envs. But I wouldn't be surprised if it works.

**Comment by djhoese** [comment]
I have a project trying to do it and I get some weird OpenGL library errors. That's when I noticed that it wasn't downloading `.dll` properly. I'll see what I can do.

CC @katherinekolman

**Comment by larsoner** [comment]
@djhoese I have no problems downloading `https://github.com/vispy/demo-data/raw/master/mesa/opengl32_mingw_64.dll` as is done in `appveyor/install_opengl.ps1`. In theory you should just be able to execute that file in your Travis run, it's what we do on AppVeyor and also Azure. For example:

https://github.com/mne-tools/mne-python/blob/master/azure-pipelines.yml#L114-L117

**Comment by djhoese** [comment]
It doesn't seem to be working:

https://travis-ci.org/ssec/sift/jobs/657913652#L1913-L1916

But I'm trying with `?raw=true` as a test now.

If  I do `wget <url>` on my Ubuntu machine I get an HTML file downloaded instead of the actual .dll file.

**Comment by larsoner** [comment]
The error I see is:
```
ERROR: The system cannot find the file specified.
```
How do you know the download failed? Could it just be that there is some permissions problem? For example if AppVeyor and Azure execute with elevated permissions by default but Travis does not, the downloader will "fail" because it tries to overwrite things in `C:\Windows\System32` which require elevated permissions

**Comment by djhoese** [comment]
Thanks. I'll look in to it.

**Comment by djhoese** [comment]
So from what I've read travis is supposed to give elevated privileges to Windows by default. So that should be fine. Rereading the powershell script I think the errors about the file not being there are the ones *before* the file is downloading which are trying to take ownership of the file and then delete it (so the download can replace it). That section of code calling the powershell script in the travis script seems to end with the file being downloaded just fine. I think I'm at another dead end:

```
    from PyQt5.QtWebEngineWidgets import QWebEngineView

E   ImportError: DLL load failed: The specified module could not be found.
```

I'm seeing funky things from ci-helpers with building my environments so have to look in to that first.

**Comment by djhoese** [comment]
Turns out Travis CI Windows doesn't support GUI applications yet as there is no support for DirectX. Had to do some really ugly DLL debugging to find that out.
